export enum PriceTier {
    CHEAP = "CHEAP", NORMAL = "NORMAL", EXPENSIVE= "EXPENSIVE", ABNORMAL_PRICE= "ABNORMAL_PRICE"
}

export enum PatternType {
    SURGE = "SURGE", SCAM = "SCAM"
}

export enum PatternMetric {
    UPPER_TUKEY_FENCE="UPPER_TUKEY_FENCE",
    LOWER_TUKEY_FENCE="LOWER_TUKEY_FENCE",
    MEMPOOL_SIZE="MEMPOOL_SIZE",
    MEMPOOL_RECOMMENDED_FEE_PER_VBYTE="MEMPOOL_RECOMMENDED_FEE_PER_VBYTE",
}